version: '2'
services:
    imscp:
        hostname: panel.kaki.sigmapix.com
        privileged: true
        build: .
        image: sigmapix/docker-imscp
        ports:
            - "8880:8880"
        networks:
            dev:
                ipv4_address: 172.18.0.6
networks:
    dev:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.254
